### PR TITLE
Added Ukrainian language and fixed custom list highlight bug

### PR DESCRIPTION
**Pull request by Beroman**
Added Ukrainian language;
Fixed custom list rendering problem when row was not highlighted if its index was above the number that can be displayed on the display at the same time

### CODE REVIEW

**Review by davetcc — COMMENTED** [review]
Many thanks for the PR.

Is there any chance you can do another pull on your branch as there's quite a few changes that would be rolled back if I merge? Otherwise, I can pull the changes from the change commits one at a time if you prefer.

**Comment by davetcc** [comment]
Don't worry, I'll manually apply the changes as best I can in the next day or so. 

Thanks for the PR.

**Comment by davetcc** [comment]
manually merged to master branch today.

**Comment by Beroman** [comment]
Thank you! I'm sorry for not getting back to you sooner.
Thank you for such a great library!

**Pull request closed without merging**
