### PR TITLE
Inform to ioAbstraction of a succesful focus move if focus really changed

### PR DESCRIPTION
**Pull request by Netsplits**
Don't let focus go to title menus which have no back button.
Only let focus move between dialog buttons when there are dialog buttons.
I adjusted to my needs, probably is not the best way to do, but hey, may be is useful.
This requires ioAbstraction PR#131 to wrok correctly.

### CODE REVIEW

**Comment by davetcc** [comment]
To be honest, I think preventing the rotary encoder from going to a specific position, that it can actually turn to will result in users thinking there is some glitch. I think this may be better fixed within MenuManager where either the navigator or manager itself could easily control such interactions. 

Also, this approach wouldn't work for keyboards and for touch screens either, as they are not represented as encoders.

Can you confirm that you are just trying to stop back / title menu items from being actioned under some circumstances? If so let's discuss putting that into menu manager so that it works in all cases.

**Comment by davetcc** [comment]
In fact if I have understood correctly, I can just bring forward a change I was going to make to the commit handler so that any subMenu, backMenu or titleMenu will result in the commit handler being called, and somehow being able to prevent the event from going any further.

**Comment by Netsplits** [comment]
I mainly did that because, for example, in root menu you can go to the title and focus is lost (you don't know what is the current selected menu item, because on root no [..] symbola appears).
But, please add the commit handler, I think can be very useful. It took me some time to handle the OK press on submenus.

**Comment by davetcc** [comment]
> I mainly did that because, for example, in root menu you can go to the title and focus is lost (you don't know what is the current selected menu item, because on root no [..] symbol appears).

We can probably also fix that very easily, to make the title item show focus properly

**Comment by Netsplits** [comment]
That should be great. Please delete this PR if you think it's not useful.
I'm sure there is a better way to do it, but I did not analyze all the innerworkings of the code, I just made it to work to my needs.

**Comment by Netsplits** [comment]
I needed to be able to make variable frame rate refresh, so added a commit to my repo. Maybe is useful...

**Comment by davetcc** [comment]
Thanks for the variable refresh rate idea. I'll get around to sorting all the points here, probably right after the 2.2 release along with a few other minor changes.

**Comment by davetcc** [comment]
I've raised issues for each of the changes now, they will all go in after 2.2 is out.

#114 #115 #116

**Comment by davetcc** [comment]
The commit handling is now there, even with the ability to stop an edit or menu navigation from even happening.
The variable rate refresh is now also supported, can be changed at any time and takes effect immediately- from the next tick. 

Can we close this now?

**Pull request closed without merging**
